swagger: "2.0"
info:
  title: "OCR API"
  description: "An API to perform OCR on images and return text"
  version: "1.0"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
paths:
  /ocr:
    post:
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: file
          in: formData
          type: file
          required: true
          description: The image file to perform OCR on
      responses:
        200:
          description: "Text extracted from the image"
          schema:
            type: object
            properties:
              text:
                type: string
        400:
          description: "Bad request if the file is not provided or is not an image"
        500:
          description: "Internal server error if an error occurs during OCR processing"
